blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<int:pk>/", views.blog_detail, name="blog_detail"),
    path("<category>/", views.blog_category, name="blog_category"),
]

nce/urls.py
from django.urls import path
from . import views
from .views import (ListOfDepart, ListOfProject, ProjectDetailView)

app_name = 'nce'
urlpatterns = [
    path("", ListOfProject.as_view(), name="index_view"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("list_of_departments", ListOfProject.as_view(), name="list_of_departments"),
]

nce_material/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls")),
    path('', include('nce.urls')),
]

blog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'category'
        # Add verbose name
        verbose_name = 'list of category'


class Post(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_created=True)
    categories = models.ManyToManyField('Category', related_name='posts')


class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

nce/models.py
from django.db import models


# Create your models here.

class Department(models.Model):
    name = models.CharField(max_length=20)


class Project(models.Model):
    title = models.CharField(max_length=270)
    contents = models.TextField()
    numbers_of_pages = models.IntegerField()
    departments = models.ManyToManyField('Department', related_name='projects')

    def __str__(self):
        return self.title

blog/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

blog/views.py
from django.shortcuts import render
from blog.models import Post, Comment
from .forms import CommentForm


# Create your views here.

def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        'posts': posts
    }
    return render(request, 'blog_index.html', context)


def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by(
        '-created_on'
    )
    context = {
        "category": category,
        'posts': posts
    }
    return render(request, 'blog_category.html', context)


def blog_detail(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                body=form.cleaned_data["body"],
                post=post
            )
            comment.save()
    comments = Comment.objects.filter(post=post)
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
    return render(request, "blog_detail.html", context)

nce/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView, DetailView)
from .models import Project, Department


class ListOfDepart(ListView):
    model = Department
    template_name = 'nceprojectsite/list_of_departments.html'


class ListOfProject(ListView):
    model = Project
    template_name = 'nceprojectsite/index.html'


class ProjectDetailView(DetailView):
    model = Project
    template_name = 'nceprojectsite/project_detail.html'

blog/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'basestyle.css' %}">
</head>
<body>
{% include 'navbar.html'%}
<div class="container">
  <div class="row">
    <div class="col-md-2">
    {%block left_block%}

    {%endblock%}
    </div>

    <div class="col-md-8">
    {%block mid_block%}
    {%endblock%}
    </div>
    <div class="col-md-2">

    {%block right_block%}

    {%endblock%}
    </div>
   </div>
   </div>
    </div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog_category.html
<!DOCTYPE html>
{%extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block content%}
<div class="col-md-8 offset-md-2">
    <h1>{{ category | title }}</h1>
    <hr>
    {% for post in posts %}
        <h2><a href="{% url 'blog_detail' post.pk%}">{{ post.title }}</a></h2>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Categories:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>

        <p>{{ post.body | slice:":400" }}...</p>

    {% endfor %}

</div>
{%endblock%}
</body>
</html>

blog/templates/blog_detail.html
<!DOCTYPE html>
{%extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <div class="row">
    <div class="col-md-2">
    <h1> HOPE THIS WORK</h1>
    {%block left_block%}

    {%endblock%}
    </div>
    <div class="col-md-8">
    {%block mid_block%}
    <h1>{{ post.title }}</h1>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h3>Leave a comment:</h3>
    <form action="/blog/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>

        <div class="form-group">

            {{ form.body }}

        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> wrote:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{%endblock%}

     <div class="col-md-2">
   <div class="sidebar search">
        <h2 class="section-title">Search</h2>
    <form action="index.html" method="post">
        <input type="text" name="search-term" class="text-input" placeholder="search...">

    </form>
    <div class="section topic">
        <h2 class="section-title">Topics</h2>
        <ul>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
        </ul>
    </div>

    {%block right_block%}

    {%endblock%}
   </div>
   </div>
</body>
</html>

blog/templates/blog_index.html
<!DOCTYPE html>
{%extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>cysofthome</title>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-2">
    <h1> HOPE THIS WORK</h1>
    {%block left_block%}

    {%endblock%}
    </div>
 <div class="col-md-8">
    {%block mid_block%}
    {% for post in posts %}
    <h2><a href="{% url 'blog_detail' post.pk%}">{{ post.title }}</a></h2>
    <small>
        {{ post.created_on.date }} |&nbsp;
        Categories:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | slice:":400" }}...</p>
    {% endfor %}
</div>
{%endblock%}

<div class="col-md-2">
   <div class="sidebar search">
        <h2 class="section-title">Search</h2>
    <form action="index.html" method="post">
        <input type="text" name="search-term" class="text-input" placeholder="search...">

    </form>
    <div class="section topic">
        <h2 class="section-title">Topics</h2>
        <ul>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
            <li><a href="#">Peams</a></li>
        </ul>
    </div>

    {%block right_block%}

    {%endblock%}
   </div>
   </div>
</body>
</html>

blog/templates/footer.html
  <footer class="page-footer bg-dark navbar-fixed-bottom">
      <div class="bg-success">
          <div class="container">
             <div class="row py-4 d-flex align-items-center">
                 <div class="col-md-12 text-center">
                     <a href="#"></a>
                     <a href="#"></a>
                     <a href="#"></a>
                     <a href="#"></a>
                     <a href="#"></a>
                 </div>
             </div>
          </div>
      </div>
      <div class="container text-center text-md-left mt-0">
          <div class="row">
              <div class="col-md-3 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">cysoft home</h6>
                  <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width:125px; height:2px">
                  <p class="mt-2">this site is built to help student on their
                  academic project and to enlighten them on things the do not know academically</p>
              </div>
              <div class="col-md-2 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">cysoft home</h6>
                  <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width:85px; height:2px">
                  <ul class="list-unstyled">
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                  </ul>
              </div>
              <div class="col-md-2 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">cysoft home</h6>
                  <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width:110px; height:2px">
                  <ul class="list-unstyled">
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                  </ul>
              </div>

              <div class="col-md-3 mx-auto mb-4">
                  <h6 class="text-uppercase font-weight-bold">cysoft home</h6>
                  <hr class="bg-success mb-4 mt-0 d-inline-block mx-auto" style="width:75px; height:2px">
                  <ul class="list-unstyled">
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                      <li class="my-2"><a href="#">link1</a> </li>
                  </ul>
              </div>
          </div>
      </div>
      <div class="bg-success footer-copyright text-center py-3 mb-0">
          <p> &copy; copyright
              <a href="#">nceprojectmaterial.com</a>

          </p>
          <p> Designed By CYSOFTHOME</p>
      </div>
  </footer>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <a class="navbar-brand" href="{%url 'nce:index_view'%}">CYSOFT-HOME</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'nce:index_view'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'blog_index'%}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Departments
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Accounting</a>
          <a class="dropdown-item" href="#">English</a>
          <a class="dropdown-item" href="#">Mathematics</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

blog/templates/nceprojectsite/index.html
<!DOCTYPE html>
{%extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block mid_block%}
{%for project in object_list%}
<h3><a href="{% url 'nce:project_detail' project.pk%}">{{project.title}}</a> </h3>
<p>{{ project.contents | slice:":400" }}...</p>
{%endfor%}
{%endblock%}
</body>
</html>

blog/templates/nceprojectsite/list_of_departments.html
<!DOCTYPE html>
{%extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <div class="col-md-2">
    {%block right_block%}
         {%for department in object_list %}
        {{department.name}}
        {%endfor%}
    {%endblock%}
    </div>
</body>
</html>

blog/templates/nceprojectsite/project_detail.html
<!DOCTYPE html>
{%extends 'base.html'%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{%block mid_block%}
<h2>{{object.title}}</h2>
<hr>
<p>{{object.contents}}</p>
{%endblock%}
</body>
</html>